trained_model_path: 'models/model.pkl'
output_preds_path: 'models/preds.pkl'
feature_params:
  target_col: 'target'
  categorical_features:
    - 'sex'
    - 'chest_pain_type'
    - 'fasting_blood_sugar'
    - 'rest_ecg'
    - 'exercise_induced_angina'
    - 'st_slope'
    - 'thalassemia'
  numerical_features:
    - 'age'
    - 'resting_blood_pressure'
    - 'cholesterol'
    - 'max_heart_rate_achieved'
    - 'st_depression'
    - 'num_major_vessels'
